<?php
namespace midi;

if(defined("_class_event_table_is_included")) {
  // do nothing since the class is already included  
} else {
  define("_class_event_table_is_included",1);
// {{{


class midiEventTable{

public static $midiEvents = array (
"80"=>array("<chanel>1</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"81"=>array("<chanel>2</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"82"=>array("<chanel>3</chanel><type>Note_off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"83"=>array("<chanel>4</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"84"=>array("<chanel>5</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"85"=>array("<chanel>6</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"86"=>array("<chanel>7</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"87"=>array("<chanel>8</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"88"=>array("<chanel>9</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"89"=>array("<chanel>10</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"8A"=>array("<chanel>11</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"8B"=>array("<chanel>12</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"8C"=>array("<chanel>13</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"8D"=>array("<chanel>14</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"8E"=>array("<chanel>15</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"8F"=>array("<chanel>16</chanel><type>Note off</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"90"=>array("<chanel>1</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"91"=>array("<chanel>2</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"92"=>array("<chanel>3</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"93"=>array("<chanel>4</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"94"=>array("<chanel>5</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"95"=>array("<chanel>6</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"96"=>array("<chanel>7</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"97"=>array("<chanel>8</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"98"=>array("<chanel>9</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"99"=>array("<chanel>10</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"9A"=>array("<chanel>11</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"9B"=>array("<chanel>12</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"9C"=>array("<chanel>13</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"9D"=>array("<chanel>14</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"9E"=>array("<chanel>15</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"9F"=>array("<chanel>16</chanel><type>Note on</type>", "Note Number (0-127)"," Note Velocity (0-127)"),
"A0"=>array("<chanel>1 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A1"=>array("<chanel>2 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A2"=>array("<chanel>3 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A3"=>array("<chanel>4 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A4"=>array("<chanel>5 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A5"=>array("<chanel>6 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A6"=>array("<chanel>7 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A7"=>array("<chanel>8 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A8"=>array("<chanel>9 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"A9"=>array("<chanel>10 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"AA"=>array("<chanel>11 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"AB"=>array("<chanel>12 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"AC"=>array("<chanel>13 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"AD"=>array("<chanel>14 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"AE"=>array("<chanel>15 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"AF"=>array("<chanel>16 Polyphonic aftertouch", "Note Number (0-127)"," Aftertouch pressure (0-127)"),
"B0"=>array("<chanel>1 Control mode change", "See MIDI controls", " See MIDI controls"),
"B1"=>array("<chanel>2 Control mode change", "See MIDI controls", " See MIDI controls"),
"B2"=>array("<chanel>3 Control mode change", "See MIDI controls", " See MIDI controls"),
"B3"=>array("<chanel>4 Control mode change", "See MIDI controls", " See MIDI controls"),
"B4"=>array("<chanel>5 Control mode change", "See MIDI controls", " See MIDI controls"),
"B5"=>array("<chanel>6 Control mode change", "See MIDI controls", " See MIDI controls"),
"B6"=>array("<chanel>7 Control mode change", "See MIDI controls", " See MIDI controls"),
"B7"=>array("<chanel>8 Control mode change", "See MIDI controls", " See MIDI controls"),
"B8"=>array("<chanel>9 Control mode change", "See MIDI controls", " See MIDI controls"),
"B9"=>array("<chanel>10 Control mode change", "See MIDI controls", " See MIDI controls"),
"BA"=>array("<chanel>11 Control mode change", "See MIDI controls", " See MIDI controls"),
"BB"=>array("<chanel>12 Control mode change", "See MIDI controls", " See MIDI controls"),
"BC"=>array("<chanel>13 Control mode change", "See MIDI controls", " See MIDI controls"),
"BD"=>array("<chanel>14 Control mode change", "See MIDI controls", " See MIDI controls"),
"BE"=>array("<chanel>15 Control mode change", "See MIDI controls", " See MIDI controls"),
"BF"=>array("<chanel>16 Control mode change", "See MIDI controls", " See MIDI controls"),
"C0"=>array("<chanel>1 Program change", " Program # (0-127)", " -"),
"C1"=>array("<chanel>2 Program change", " Program # (0-127)", " -"),
"C2"=>array("<chanel>3 Program change", " Program # (0-127)", " -"),
"C3"=>array("<chanel>4 Program change", " Program # (0-127)", " -"),
"C4"=>array("<chanel>5 Program change", " Program # (0-127)", " -"),
"C5"=>array("<chanel>6 Program change", " Program # (0-127)", " -"),
"C6"=>array("<chanel>7 Program change", " Program # (0-127)", " -"),
"C7"=>array("<chanel>8 Program change", " Program # (0-127)", " -"),
"C8"=>array("<chanel>9 Program change", " Program # (0-127)", " -"),
"C9"=>array("<chanel>10 Program change", "Program # (0-127)", " -"),
"CA"=>array("<chanel>11 Program change", "Program # (0-127)", " -"),
"CB"=>array("<chanel>12 Program change", "Program # (0-127)", " -"),
"CC"=>array("<chanel>13 Program change", "Program # (0-127)", " -"),
"CD"=>array("<chanel>14 Program change", "Program # (0-127)", " -"),
"CE"=>array("<chanel>15 Program change", "Program # (0-127)", " -"),
"CF"=>array("<chanel>16 Program change", "Program # (0-127)", " -"),
"D0"=>array("<chanel>1 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D1"=>array("<chanel>2 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D2"=>array("<chanel>3 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D3"=>array("<chanel>4 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D4"=>array("<chanel>5 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D5"=>array("<chanel>6 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D6"=>array("<chanel>7 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D7"=>array("<chanel>8 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D8"=>array("<chanel>9 Channel aftertouch", " Aftertouch pressure (0-127)", " -"),
"D9"=>array("<chanel>10 Channel aftertouch", "Aftertouch pressure (0-127)", " -"),
"DA"=>array("<chanel>11 Channel aftertouch", "Aftertouch pressure (0-127)", " -"),
"DB"=>array("<chanel>12 Channel aftertouch", "Aftertouch pressure (0-127)", " -"),
"DC"=>array("<chanel>13 Channel aftertouch", "Aftertouch pressure (0-127)", " -"),
"DD"=>array("<chanel>14 Channel aftertouch", "Aftertouch pressure (0-127)", " -"),
"DE"=>array("<chanel>15 Channel aftertouch", "Aftertouch pressure (0-127)", " -"),
"DF"=>array("<chanel>16 Channel aftertouch", "Aftertouch pressure (0-127)", " -"),
"E0"=>array("<chanel>1 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E1"=>array("<chanel>2 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E2"=>array("<chanel>3 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E3"=>array("<chanel>4 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E4"=>array("<chanel>5 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E5"=>array("<chanel>6 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E6"=>array("<chanel>7 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E7"=>array("<chanel>8 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E8"=>array("<chanel>9 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"E9"=>array("<chanel>10 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"EA"=>array("<chanel>11 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"EB"=>array("<chanel>12 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"EC"=>array("<chanel>13 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"ED"=>array("<chanel>14 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"EE"=>array("<chanel>15 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"EF"=>array("<chanel>16 Pitch wheel range", "Pitch wheel LSB (0-127)", "Pitch wheel MSB (0-127)"),
"F0"=>array("System Exclusive","**", "**"),
"F1"=>array("System Common - undefined","   -","   -"),
"F2"=>array("Sys Com Song Position Pntr","  LSB"," MSB"),
"F3"=>array("Sys Com Song Select(Song #)"," (0-127)"," -"),
"F4"=>array("System Common - undefined","   -","   -"),
"F5"=>array("System Common - undefined","   - ","  -"),
"F6"=>array("Sys Com tune request ","   -  "," -"),
"F7"=>array("Sys Com-end of SysEx (EOX)","  -   ","-"),
"F8"=>array("Sys real time timing clock","  - ","  -"),
"F9"=>array("Sys real time undefined"," -  "," -"),
"FA"=>array("Sys real time start"," -   ","-"),
"FB"=>array("Sys real time continue","  -  "," -"),
"FC"=>array("Sys real time stop","  -   ","-"),
"FD"=>array("Sys real time undefined"," -   ","-"),
"FE"=>array("Sys real time active sensing","    -   ","-"),
"FF"=>array("Sys real time sys reset"," -","   -")
);


}
}
?>